package payment

import("bytes";"context";"encoding/base64";"encoding/json";"errors";"fmt";"io";"net/http";"net/url";"strings";"time")
type PayPal struct{BaseURL,ClientID,Secret string;HTTP *http.Client}
func NewPayPal(baseURL,clientID,secret string)*PayPal{return &PayPal{BaseURL:strings.TrimRight(baseURL,"/"),ClientID:clientID,Secret:secret,HTTP:&http.Client{Timeout:12*time.Second}}}
func(p *PayPal)Enabled()bool{return p.BaseURL!=""&&p.ClientID!=""&&p.Secret!=""}
func(p *PayPal)accessToken(ctx context.Context)(string,error){if !p.Enabled(){return "",errors.New("PayPal is not configured")};body:=url.Values{"grant_type":{"client_credentials"}}.Encode();req,err:=http.NewRequestWithContext(ctx,http.MethodPost,p.BaseURL+"/v1/oauth2/token",strings.NewReader(body));if err!=nil{return "",err};auth:=base64.StdEncoding.EncodeToString([]byte(p.ClientID+":"+p.Secret));req.Header.Set("Authorization","Basic "+auth);req.Header.Set("Content-Type","application/x-www-form-urlencoded");var result struct{AccessToken string `json:"access_token"`};if err:=p.doJSON(req,&result);err!=nil{return "",err};if result.AccessToken==""{return "",errors.New("PayPal returned an empty access token")};return result.AccessToken,nil}
func(p *PayPal)CreateOrder(ctx context.Context,amount float64)(map[string]any,error){token,err:=p.accessToken(ctx);if err!=nil{return nil,err};payload:=map[string]any{"intent":"CAPTURE","purchase_units":[]any{map[string]any{"amount":map[string]string{"currency_code":"EUR","value":fmt.Sprintf("%.2f",amount)}}}};body,_:=json.Marshal(payload);req,err:=http.NewRequestWithContext(ctx,http.MethodPost,p.BaseURL+"/v2/checkout/orders",bytes.NewReader(body));if err!=nil{return nil,err};req.Header.Set("Authorization","Bearer "+token);req.Header.Set("Content-Type","application/json");var result map[string]any;if err:=p.doJSON(req,&result);err!=nil{return nil,err};return result,nil}
func(p *PayPal)CaptureOrder(ctx context.Context,orderID string)(map[string]any,error){if strings.TrimSpace(orderID)==""{return nil,errors.New("missing PayPal order id")};token,err:=p.accessToken(ctx);if err!=nil{return nil,err};req,err:=http.NewRequestWithContext(ctx,http.MethodPost,p.BaseURL+"/v2/checkout/orders/"+url.PathEscape(orderID)+"/capture",http.NoBody);if err!=nil{return nil,err};req.Header.Set("Authorization","Bearer "+token);req.Header.Set("Content-Type","application/json");var result map[string]any;if err:=p.doJSON(req,&result);err!=nil{return nil,err};return result,nil}
func(p *PayPal)doJSON(req *http.Request,out any)error{resp,err:=p.HTTP.Do(req);if err!=nil{return err};defer resp.Body.Close();if resp.StatusCode<200||resp.StatusCode>=300{body,_:=io.ReadAll(io.LimitReader(resp.Body,4096));return fmt.Errorf("PayPal request failed (%d): %s",resp.StatusCode,strings.TrimSpace(string(body)))};dec:=json.NewDecoder(io.LimitReader(resp.Body,2<<20));if err:=dec.Decode(out);err!=nil{return fmt.Errorf("decode PayPal response: %w",err)};return nil}
